baseURL = "https://covid.molssi.org/"
languageCode = "en-us"
title = "COVID-19 Molecular Structure and Therapeutics Hub"
theme = "minimal"
# disqusShortname = "username" # delete this to disable disqus comments
# googleAnalytics = ""

# Additional custom parameters
# Ignore README files meant for GitHub
ignoreFiles = ["README.md$"]

[params]
    author = "MolSSI and BioExcel"
    description = "Aggregating critical information to accelerate drug discovery for the molecular modeling and simulation community."
    githubUsername = "#"
    accent = "red"
    showBorder = true
    backgroundColor = "white"
    font = "Raleway" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "default"
    highlightLanguages = ["go", "haskell", "kotlin", "scala", "swift"]

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/proteins"
    hasChildren = true
    name = "Proteins"
    weight = 2

[[menu.main]]
    url = "/therapeutics"
    name = "Therapeutics"
    weight = 3

[[menu.main]]
    url = "/contributing/"
    name = "Contributing"
    weight = 4

[[menu.main]]
    hasChildren = true
    name = "About"
    weight = 5

    [[menu.main]]
        parent = "About"
        url = "/about/"
        name = "About the Exchange"
        weight = 1

    [[menu.main]]
        parent = "About"
        url = "/collaborating/"
        name = "Collaborating"
        weight = 2

    [[menu.main]]
        parent = "About"
        url = "/teams/"
        name = "Teams"
        weight = 3

# Social icons to be shown on the right-hand side of the navigation bar.
# The "name" field should match the name of the icon in Font Awesome.
# The list of available icons can be found at http://fontawesome.io/icons.

[[menu.icon]]
    url = "https://github.com/molssi/covid"
    name = "github"
    weight = 1

[[menu.icon]]
    url = "mailto:info@molssi.org"
    name = "envelope-o"
    weight = 2

[[menu.icon]]
    url = "https://twitter.com/MolSSI_NSF/"
    name = "twitter"
    weight = 3
