baseURL = "https://covid.molssi.org/"
languageCode = "en-us"
title = "COVID-19 Molecular Structure and Therapeutics Hub"
theme = "minimal"
# disqusShortname = "username" # delete this to disable disqus comments
# googleAnalytics = ""

# Additional custom parameters
# Ignore README files meant for GitHub
ignoreFiles = ["README.md$"]

[params]
    author = "MolSSI and BioExcel"
    description = "Aggregating critical information to accelerate drug discovery for the molecular modeling and simulation community."
    githubUsername = "#"
    accent = "red"
    showBorder = true
    backgroundColor = "white"
    font = "Raleway" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "default"
    highlightLanguages = ["go", "haskell", "kotlin", "scala", "swift"]

[[menu.main]]
    hasChildren = true
    name = "Biology"
    weight = 1

    [[menu.main]]
        parent = "Biology"
        url = "/proteins/"
        name = "Proteins"
        weight = 1

    [[menu.main]]
        parent = "Biology"
        url = "/targets/"
        name = "Target Modalities"
        weight = 2


[[menu.main]]
    hasChildren = true
    name = "Viral/Host Structural Data"
    weight = 2

    [[menu.main]]
        parent = "Viral/Host Structural Data"
        url = "/structures"
        name = "Structures"
        weight = 1

    [[menu.main]]
        parent = "Viral/Host Structural Data"
        url = "/models"
        name = "Models"
        weight = 2

    [[menu.main]]
        parent = "Viral/Host Structural Data"
        url = "/simulations"
        name = "Simulations"
        weight = 2

[[menu.main]]
    hasChildern = true
    url = "/therapeutics"
    name = "Therapeutics"
    weight = 3

    [[menu.main]]
        parent = "Therapeutics"
        url = "/therapeutics"
        name = "All Therapeutics"
        weight = 1

    [[menu.main]]
        parent = "Therapeutics"
        url = "/therapeutics#antiviral"
        name = "Antivirals"
        weight = 2

    [[menu.main]]
        parent = "Therapeutics"
        url = "/therapeutics#small-molecule"
        name = "Small Molecules"
        weight = 3

    [[menu.main]]
        parent = "Therapeutics"
        url = "/therapeutics#peptide"
        name = "Peptides"
        weight = 4

    [[menu.main]]
        parent = "Therapeutics"
        url = "/therapeutics#immunotherapy"
        name = "Immunotherapies"
        weight = 5

    [[menu.main]]
        parent = "Therapeutics"
        url = "/therapeutics#antibody"
        name = "Antibodies"
        weight = 6

    [[menu.main]]
        parent = "Therapeutics"
        url = "/therapeutics#ext_res_therapeutics"
        name = "Drug Databases"
        weight = 7


[[menu.main]]
    hasChildren = true
    name = "Contribution"
    weight = 9

    [[menu.main]]
        parent = "Contribution"
        url = "/contributors/"
        name = "Contributors"
        weight = 1
    
    [[menu.main]]
        parent = "Contribution"
        url = "/contributing/"
        name = "How to Contribute"
        weight = 2


[[menu.main]]
    hasChildren = true
    name = "About"
    weight = 600

    [[menu.main]]
        parent = "About"
        url = "/about/"
        name = "About The Hub"
        weight = 1

    [[menu.main]]
        parent = "About"
        url = "/links/"
        name = "External Resources"
        weight = 3

    [[menu.main]]
        parent = "About"
        url = "/glossary/"
        name = "Glossary"
        weight = 4
        
#    [[menu.main]]
#        parent = "About"
#        url = "/teams/"
#        name = "Teams"
#        weight = 3

# Social icons to be shown on the right-hand side of the navigation bar.
# The "name" field should match the name of the icon in Font Awesome.
# The list of available icons can be found at http://fontawesome.io/icons.

[[menu.icon]]
    url = "/"
    name = "home"
    weight = 1

[[menu.icon]]
    url = "https://github.com/molssi/covid"
    name = "github"
    weight = 2

[[menu.icon]]
    url = "mailto:info@molssi.org"
    name = "envelope-o"
    weight = 3

[[menu.icon]]
    url = "https://twitter.com/MolSSI_NSF/"
    name = "twitter"
    weight = 4
